org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Djava.io.tmpdir=/mnt/ALL/LinuxDev/caches/.caches_mount/tmp
android.useAndroidX=true
android.enableJetifier=true
org.gradle.java.home=/mnt/ALL/LinuxDev/Android/Android Studio/jbr
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
kotlin.daemon.jvm.options=-Djava.io.tmpdir=/mnt/ALL/LinuxDev/caches/.caches_mount/tmp
org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.auto-download=false
kotlin.daemon.enabled=false
android.skipBuildDependencyValidation=true
